# Generated by Django 5.2.2 on 2025-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='image.png', upload_to='profile_pictures/'),
        ),
    ]
